In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler


In [2]:
data= pd.read_csv("/Users/ekcs011/Downloads/Decision tree/winequality_red.csv")

In [3]:
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
x = data.drop(columns='quality')

In [5]:
x 

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [6]:
y = data.quality

In [7]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [8]:
x_train , x_test, y_train,y_test = train_test_split(x,y,test_size = .25,random_state = 30)

In [9]:
knn = KNeighborsClassifier()

In [10]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
param = {
    'n_neighbors' : [3,5,7,9,12,15,17,21],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size ': [10, 15, 20, 25, 30, 35, 40, 45],
    'p':[1,2],
    'weights': ['uniform', 'distance']
    
    
}

In [12]:
grid_cv = GridSearchCV(knn,param_grid = param )

In [13]:
grid_cv.fit(x_train,y_train)

ValueError: Invalid parameter leaf_size  for estimator KNeighborsClassifier(). Check the list of available parameters with `estimator.get_params().keys()`.

In [14]:
grid_cv.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [15]:
knn = KNeighborsClassifier(n_neighbors=17,p=1,weights='distance',leaf_size=10, algorithm='auto')

In [16]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=17, p=1, weights='distance')

In [17]:
knn.score

<bound method ClassifierMixin.score of KNeighborsClassifier(leaf_size=10, n_neighbors=17, p=1, weights='distance')>

In [18]:
knn.score(x_test,y_test)

0.6275

In [19]:
import pickle
pickle.dump(knn, open("knn.pkl","wb"))

In [20]:
pwd

'/Users/ekcs011'

In [21]:
cd

/Users/ekcs011


In [22]:
ls

 Character-control-using-body-posture.ipynb
11 April Live class opps.ipynb
15th May live class.ipynb
23 May Live Class(API & Flask).ipynb
24 July Data Visualization.ipynb
25th July Seaborn.ipynb
3 Oct Live Class DecisionTreeClassifier.ipynb
4 Sep Classs.ipynb
5 June Live Class.ipynb
5 June Live Class1.ipynb
8 Augest EDA.ipynb
8 May Live Class.ipynb
9 May Class .ipynb
Applications/
April10 Live class.ipynb
Augest 7 EDA .ipynb
Basic Python Assignment 16.ipynb
Cassandra Leatcure.ipynb
Class task .ipynb
Data Visualization 18 June.ipynb
Decision Trees (DTs) & Random Forest live Class 9 and 10 Oct.ipynb
Decision Trees (DTs) & Random Forest.ipynb
Decision_tree.ipynb
Desktop/
Diabetes Prediction System.ipynb
Documents/
Downloads/
EVALML Automating NLP.ipynb
End to End machine Learning Project Chapter 2 Hands on ML Book.ipynb
First Machine Learning Model(linear Regression & MultiLinear Regression).ipynb
Game_play_with_body_posture.ipynb
House Price Prediction.ipynb
HousePricePrediction1/
Hypoth

In [23]:
knn.predict(x_test)

array([6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 7, 6, 5, 5, 6, 6, 5, 6,
       5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 7, 6, 6, 5, 7, 6, 6, 6, 5,
       5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 7, 5,
       5, 6, 5, 5, 5, 5, 5, 5, 6, 6, 7, 5, 5, 6, 6, 7, 6, 6, 5, 5, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 7, 5, 5, 6, 5, 5, 7, 6, 6, 6, 5, 7, 5,
       5, 5, 5, 6, 6, 6, 5, 6, 6, 6, 6, 6, 7, 6, 7, 5, 6, 6, 6, 6, 5, 5,
       5, 5, 7, 6, 5, 5, 6, 7, 5, 5, 5, 5, 6, 5, 5, 5, 7, 7, 5, 5, 6, 5,
       5, 7, 5, 6, 4, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 6, 6, 6, 7, 6, 7, 5, 5, 5, 5, 6, 5, 6, 5,
       5, 6, 7, 5, 6, 5, 5, 7, 7, 6, 6, 6, 6, 5, 5, 5, 5, 5, 6, 5, 5, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 7, 5, 5, 5, 6, 6, 6, 5, 5,
       6, 6, 6, 6, 6, 5, 6, 5, 5, 7, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6,
       5, 5, 6, 6, 6, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5,
       7, 5, 5, 7, 5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 5,

In [24]:
x_test.iloc[0]

fixed acidity           10.00000
volatile acidity         0.41000
citric acid              0.45000
residual sugar           6.20000
chlorides                0.07100
free sulfur dioxide      6.00000
total sulfur dioxide    14.00000
density                  0.99702
pH                       3.21000
sulphates                0.49000
alcohol                 11.80000
Name: 1147, dtype: float64

In [25]:
knn.predict([x_test.iloc[0]])

array([6])

### Support Vector Machine

In [26]:
data

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [27]:
from sklearn.svm import SVC

In [28]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [29]:
svc.score(x_test,y_test)

0.54

In [35]:
param = {"kernel":['linear', 'poly', 'rbf', 'sigmoid'],
#         'C':[.1,.4,.6,100,200,500],
#         'gamma':[.001,.1,.4,.003]
         
    
}

svm_grid = GridSearchCV(svc, param_grid = param,verbose=3)


In [38]:
svm_grid.fit(x_train,y_train)

Fitting 5 folds for each of 4 candidates, totalling 20 fits
[CV 1/5] END .....................kernel=linear;, score=0.567 total time=   8.9s
[CV 2/5] END .....................kernel=linear;, score=0.571 total time=   7.0s
[CV 3/5] END .....................kernel=linear;, score=0.596 total time=   4.4s
[CV 4/5] END .....................kernel=linear;, score=0.571 total time=   8.2s
[CV 5/5] END .....................kernel=linear;, score=0.561 total time=   6.2s
[CV 1/5] END .......................kernel=poly;, score=0.487 total time=   0.2s
[CV 2/5] END .......................kernel=poly;, score=0.471 total time=   0.2s
[CV 3/5] END .......................kernel=poly;, score=0.467 total time=   0.1s
[CV 4/5] END .......................kernel=poly;, score=0.492 total time=   0.2s
[CV 5/5] END .......................kernel=poly;, score=0.448 total time=   0.1s
[CV 1/5] END ........................kernel=rbf;, score=0.475 total time=   0.1s
[CV 2/5] END ........................kernel=rbf;,

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [39]:
svm_grid.best_params_

{'kernel': 'linear'}

In [40]:
svc1 = SVC(kernel='linear')
svc1.fit(x_train,y_train)

SVC(kernel='linear')

In [41]:
svc1.score(x_test,y_test)

0.59

In [ ]:
pd.read_csv()

##SUPPORT VECTOR REGRESSION

##  SUPPORT VECTOR REGRESSION(need to revise and write code)

In [45]:
from sklearn.svm import SVR

#  STACKING 

In [47]:
## In stacking we can use  multiple models

In [48]:
import pandas as pd
import numpy as np
from skleran.neighbors import KNe

In [55]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split , GridSearchCV
from sklearn.metrics import accuracy_score , confusion_matrix , roc_auc_score , roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [56]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [57]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

### Dividing the data in the stacking 

In [69]:
train, val_train, test, val_test = train_test_split(x,y,test_size=.50, random_state=30)

In [70]:
x_train , x_test, y_train,y_test = train_test_split(train,test,test_size = .15,random_state = 30)

In [71]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [72]:
knn.score(x_test,y_test)

0.5833333333333334

In [73]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [74]:
svc.score(x_test,y_test)

0.5083333333333333

In [76]:
prediction_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train)

In [78]:
prediction_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 5, 5,
       6, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 4, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 7, 6, 5, 5, 5, 6,
       5, 5, 5, 7, 6, 6, 6, 7, 5, 6, 5, 5, 5, 6, 5, 7, 6, 5, 6, 5, 7, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 7, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 5, 5, 5, 5,
       6, 5, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 4, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6,
       5, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6,
       7, 5, 6, 7, 5, 4, 6, 7, 5, 5, 6, 5, 5, 6, 5,

In [79]:
prediction_svc

array([6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [80]:
np.column_stack((prediction_knn,prediction_svc))

array([[7, 6],
       [5, 6],
       [6, 6],
       ...,
       [6, 6],
       [6, 6],
       [5, 5]])

In [81]:
input3  = np.column_stack((prediction_knn,prediction_svc))

In [82]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  6  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [83]:
rf = RandomForestClassifier()

In [86]:
rf.fit(input3, output) ## needs to define the Output 

TypeError: fit() missing 1 required positional argument: 'y'

In [87]:
rf.score(x_test,y_test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [88]:
knn
svc
rf

RandomForestClassifier()

In [92]:
knn_output =knn.predict(x_test)
scv_output = svc.predict(x_test)

In [98]:
output_stack1 = np.column_stack((knn_output,scv_output))

In [99]:
rf.predict(output_stack1)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [100]:
rf.score(output_stack1,y_test)

NotFittedError: This RandomForestClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.