In [1]:
import numpy as np

In [2]:
import array

In [3]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5,"narender",4+8j])

array(['1', '2', '3', '4', '5', 'narender', '(4+8j)'], dtype='<U21')

In [7]:
np.array([1,2,3,4,5,6.0])

array([1., 2., 3., 4., 5., 6.])

In [11]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [12]:
np.array([[1,3],[3,4],[6,7,8]])

<ipython-input-12-2fc331c0f648>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [13]:
np.array([[[1,3]],[[3,4]],[[6,7,8]]])

<ipython-input-13-675db3d7199d>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[[1,3]],[[3,4]],[[6,7,8]]])


array([[list([1, 3])],
       [list([3, 4])],
       [list([6, 7, 8])]], dtype=object)

In [16]:
np.array([1,2,3], ndmin=8)

array([[[[[[[[1, 2, 3]]]]]]]])

In [18]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [52]:
arr=np.array([(1,2), (4,5)],dtype=[("a",'<i2'),("b",'<i8')])

In [53]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [54]:
arr[0][0]

1

In [55]:
type(arr[0][0])

numpy.int16

In [56]:
arr[0][1]

2

In [57]:
type(arr[0][1])

numpy.int64

In [58]:
arr = np.array([[1,3],[3,4],[6,7]])

In [62]:
arr

array([[1, 3],
       [3, 4],
       [6, 7]])

In [67]:
type(arr[0][1])

numpy.int64

In [69]:
np.matrix(arr)

matrix([[1, 3],
        [3, 4],
        [6, 7]])

In [70]:
np.mat(arr)

matrix([[1, 3],
        [3, 4],
        [6, 7]])

In [79]:
l = [1,2,3,4,5,5,6,6]

In [72]:
np.array(l)

array([1, 2, 3, 4, 5, 5, 6, 6])

In [74]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 5, 6, 6])

In [78]:
np.asarray(mat)

array([1, 2, 3, 4, 5, 5, 6, 6])

In [80]:
issubclass(np.matrix,np.ndarray)

True

In [81]:
issubclass(np.ndarray, np.matrix)

False

In [82]:
arr

array([[1, 3],
       [3, 4],
       [6, 7]])

In [83]:
a = arr

In [84]:
b = np.copy(arr)

In [85]:
b

array([[1, 3],
       [3, 4],
       [6, 7]])

In [86]:
arr[0][0]= 67

In [87]:
arr

array([[67,  3],
       [ 3,  4],
       [ 6,  7]])

In [88]:
b

array([[1, 3],
       [3, 4],
       [6, 7]])

In [89]:
for i in arr:
    print(i)

[67  3]
[3 4]
[6 7]


In [92]:
np.fromfunction(lambda i,j :i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [93]:
np.fromfunction(lambda i,j :i/j,(4,4))

<ipython-input-93-5264f4c4c0d6>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(4,4))
<ipython-input-93-5264f4c4c0d6>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [96]:
(i*i for i in range(5))

<generator object <genexpr> at 0x115336f90>

In [97]:
def test(x):
    yield x

In [101]:
gen = test(5)

In [102]:
gen

<generator object test at 0x11534c740>

In [106]:
np.fromiter(range(5),dtype = int)

array([0, 1, 2, 3, 4])

In [111]:
np.fromstring('1,2,3,4,5',sep = ', ',dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [113]:
arr = np.array(1)

In [131]:
arr1 = np.array([[[1,2,3,4],[43,54,35],[4,5,6,76]]])

<ipython-input-131-a215f845a577>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr1 = np.array([[[1,2,3,4],[43,54,35],[4,5,6,76]]])


In [132]:
arr1

array([[list([1, 2, 3, 4]), list([43, 54, 35]), list([4, 5, 6, 76])]],
      dtype=object)

In [133]:
type(arr1)

numpy.ndarray

In [134]:
arr1.ndim

2

In [135]:
arr1.size

3

In [136]:
arr1.shape

(1, 3)

In [137]:
arr1.dtype

dtype('O')

In [138]:
arr.size

1

In [139]:
arr

array(1)

In [140]:
arr.ndim

0

In [141]:
arr.shape

()

In [147]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7],[1,2,3,4],[4,5,6,7]]])

In [148]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [149]:
arr2.size

16

## 

In [150]:
arr2.ndim

3

In [151]:
arr2.shape

(1, 4, 4)

In [155]:
list(range(5))

[0, 1, 2, 3, 4]

In [159]:
np.arange(6.6,9,.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [160]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [161]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [171]:
np.linspace(1,8)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [172]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [173]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [177]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [2]:
np.ones(4)

NameError: name 'np' is not defined

In [182]:
np.ones((2,3,1))+50000

array([[[50001.],
        [50001.],
        [50001.]],

       [[50001.],
        [50001.],
        [50001.]]])

In [183]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [187]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [192]:
np.linspace(2,3,4,endpoint=False,axis=0)

array([2.  , 2.25, 2.5 , 2.75])

In [194]:
np.linspace([2,3],4,endpoint=False,axis=1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [3.  , 3.02, 3.04, 3.06, 3.08, 3.1 , 3.12, 3.14, 3.16, 3.18, 3.2 ,
        3.22, 3.24, 3.26, 3.28, 3.3 , 3.32, 3.34, 3.36, 3.38, 3.4 , 3.42,
        3.44, 3.46, 3.48, 3.5 , 3.52, 3.54, 3.56, 3.58, 3.6 , 3.62, 3.64,
        3.66, 3.68, 3.7 , 3.72, 3.74, 3.76, 3.78, 3.8 , 3.82, 3.84, 3.86,
        3.88, 3.9 , 3.92, 3.94, 3.96, 3.98]])

In [196]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [198]:
np.logspace([2,3],5,axis=1)

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [202]:
np.logspace([2,4],[3],axis=1)

array([[  100.        ,   104.81131342,   109.8541142 ,   115.13953993,
          120.67926406,   126.48552169,   132.57113656,   138.94954944,
          145.63484775,   152.64179672,   159.98587196,   167.68329368,
          175.75106249,   184.20699693,   193.06977289,   202.35896477,
          212.09508879,   222.29964825,   232.99518105,   244.20530945,
          255.95479227,   268.26957953,   281.1768698 ,   294.70517026,
          308.88435965,   323.74575428,   339.32217719,   355.64803062,
          372.75937203,   390.69399371,   409.49150624,   429.19342601,
          449.8432669 ,   471.48663635,   494.17133613,   517.94746792,
          542.86754393,   568.9866029 ,   596.36233166,   625.05519253,
          655.12855686,   686.648845  ,   719.685673  ,   754.31200634,
          790.60432109,   828.64277285,   868.51137375,   910.29817799,
          954.09547635,  1000.        ],
       [10000.        ,  9540.9547635 ,  9102.98177992,  8685.11373751,
         8286.42772855,

In [204]:
d = np.linspace(4,5,40)

In [205]:
d

array([4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
       4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
       4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
       4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949,
       4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
       4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
       4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
       4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ])

In [206]:
d.ndim

1

In [207]:
d.shape

(40,)

In [219]:
d.reshape(40,1)

array([[4.        ],
       [4.02564103],
       [4.05128205],
       [4.07692308],
       [4.1025641 ],
       [4.12820513],
       [4.15384615],
       [4.17948718],
       [4.20512821],
       [4.23076923],
       [4.25641026],
       [4.28205128],
       [4.30769231],
       [4.33333333],
       [4.35897436],
       [4.38461538],
       [4.41025641],
       [4.43589744],
       [4.46153846],
       [4.48717949],
       [4.51282051],
       [4.53846154],
       [4.56410256],
       [4.58974359],
       [4.61538462],
       [4.64102564],
       [4.66666667],
       [4.69230769],
       [4.71794872],
       [4.74358974],
       [4.76923077],
       [4.79487179],
       [4.82051282],
       [4.84615385],
       [4.87179487],
       [4.8974359 ],
       [4.92307692],
       [4.94871795],
       [4.97435897],
       [5.        ]])

In [218]:
d.reshape(2,1,20)

array([[[4.        , 4.02564103, 4.05128205, 4.07692308, 4.1025641 ,
         4.12820513, 4.15384615, 4.17948718, 4.20512821, 4.23076923,
         4.25641026, 4.28205128, 4.30769231, 4.33333333, 4.35897436,
         4.38461538, 4.41025641, 4.43589744, 4.46153846, 4.48717949]],

       [[4.51282051, 4.53846154, 4.56410256, 4.58974359, 4.61538462,
         4.64102564, 4.66666667, 4.69230769, 4.71794872, 4.74358974,
         4.76923077, 4.79487179, 4.82051282, 4.84615385, 4.87179487,
         4.8974359 , 4.92307692, 4.94871795, 4.97435897, 5.        ]]])

In [221]:
np.random.rand(30)

array([0.46824417, 0.47150604, 0.32885091, 0.58627838, 0.6995401 ,
       0.11501942, 0.52682903, 0.75325088, 0.43685536, 0.42850523,
       0.14609795, 0.58589244, 0.49374464, 0.78952435, 0.05954965,
       0.13229701, 0.05694043, 0.48435752, 0.47783495, 0.38093626,
       0.78282174, 0.28748002, 0.52317076, 0.41494501, 0.01841673,
       0.10281298, 0.58962961, 0.61236452, 0.24906898, 0.47734134])

In [226]:
np.random.randn(2,5,4)

array([[[-1.38920106,  3.05170368, -0.43974991,  0.81111805],
        [-0.07897559, -1.00901279,  1.50971696,  0.79642801],
        [ 0.530293  ,  2.18924313, -0.43427155, -0.39499913],
        [ 2.04789561, -0.47992116,  0.56953089, -0.92306132],
        [ 1.93955583, -0.70612536, -0.80182268,  0.70337741]],

       [[-1.03835722,  0.14468561, -0.91925913, -1.69819368],
        [ 0.5666276 , -2.19441464,  0.40775813, -0.68267793],
        [ 1.38270496, -1.40625124,  0.05688119, -1.38567718],
        [-0.50305335, -1.78653665,  1.43687491,  2.17268659],
        [ 1.90372419, -0.51270229,  0.80885615, -0.00827659]]])

In [229]:
np.random.randint(4)

2

In [230]:
arr = np.random.randint(3,9,(3,3))

In [231]:
arr

array([[3, 7, 5],
       [4, 8, 4],
       [7, 8, 7]])

In [232]:
arr.reshape(1,9)

array([[3, 7, 5, 4, 8, 4, 7, 8, 7]])

In [233]:
arr.reshape(9,1)

array([[3],
       [7],
       [5],
       [4],
       [8],
       [4],
       [7],
       [8],
       [7]])

In [234]:
arr.reshape(1,1,9)

array([[[3, 7, 5, 4, 8, 4, 7, 8, 7]]])

In [235]:
arr.reshape(3,3,1)

array([[[3],
        [7],
        [5]],

       [[4],
        [8],
        [4]],

       [[7],
        [8],
        [7]]])

In [3]:
import numpy as np

In [6]:
df = {'key1':[1,2,3,4,np.nan]},{'key2':["narender","beniwal",4,5,6]}

In [7]:
df

({'key1': [1, 2, 3, 4, nan]}, {'key2': ['narender', 'beniwal', 4, 5, 6]})